# 2020 Fall Introduction to AI Programming II : NumPy Practice

## Goals 
   In this Lab session, you practice writing Python NumPy moudle 
   Most of the statistical analysis which needs data to be stored in memory uses NumPy. 
   You will be looking into the following topics in here.

Issues covered:
  1. Why NumPy and Not Python lists
  2. How to create NumPy Arrays
  3. Create N-Dimensional Array
  4. Mathematical Operations and Array Calculations 

## 1. Why NumPy and Not Python lists
   

NumPy provides efficient storage and better ways of handling data for Mathematical Operations.

NumPy is the fundamental package for scientific computing with Python. Extremely useful!!

links used:
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html    

## 2. How to create NumPy Arrays

 - import the "numpy" library as "np"

In [ ]:
import numpy as np
print(np.__version__)

1.16.4


- using .array(....) function

In [ ]:
np_arr = np.array([1,2,3,4,5,6])

In [ ]:
np_arr  #  print(np_arr)

array([1, 2, 3, 4, 5, 6])

In [ ]:
len(np_arr)

6

In [ ]:
py_arr = [1,2,3,4,5,6]

In [ ]:
py_arr

[1, 2, 3, 4, 5, 6]

In [ ]:
len(py_arr)

6

- Check the difference between python array and numpy array

In [ ]:
# insertion by string 
py_arr= [1,2,3,4,"Hello", 5,6]

In [ ]:
py_arr

[1, 2, 3, 4, 'Hello', 5, 6]

In [ ]:
[type(item) for item in py_arr]

[int, int, int, int, str, int, int]

In [ ]:
np_arr = np.array([1,2,3,"Hello", 4,5,6])

In [ ]:
np_arr
# Remember that unlike Python lists,
# NumPy is constrained to arrays that all contain the same type. 
# If types do not match, NumPy will upcast if possible 
# (here, integers are up-cast to stringtype):

array(['1', '2', '3', 'Hello', '4', '5', '6'], dtype='<U11')

 - Create a list with values 1 to 10 and assign it to the variable "list1"
 - Create an integer array from list1 and assign it
 - Check the data type of each array (use the attribute "dtype")

In [ ]:
list1= range(1, 11)
np_arr = np.array(list1, dtype = np.int32)   # np_arr = np.array(list1, "i") 
print(np_arr, np_arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10] int32


 - Create a list with values 1 to 10 and assign it to the variable "list1"
 - Create an array of floats from list1 and assign it
 - Check the data type of each array (use the attribute "dtype")

In [ ]:
list1 = range(1,11)

np_arr = np.array(list1, dtype = np.float64)
print(np_arr, np_arr.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] float64


## 3. Create N-Dimensional Array

- using .array() and many other function   # create numpy array
- using .reshape() function   # reshapes the array without changing the original shape
- using .arange() function    # create sequence of numbers in array
- using .empty()              # to get a matrix of all random numbers
- using .zeros() and ones()   # numpy provides the utility to create some usual matrices which are commonly used
- using .diag()               # diagonal elements   np.diag([1,1,1,1])
- using .ravel() function 

- Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy.

<script src="https://npmcdn.com/jupyter-js-widgets@~1.2.0/dist/embed.js"></script><img src='https://www.oreilly.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png'><script type="application/vnd.jupyter-embedded-widgets">{}</script>

In [ ]:
import numpy as np
# Create an array filled with a linear sequence
# Starting at 0, ending at 10, stepping by 1
# (this is similar to the built-in range() function)
np_arr=np.arange(0,10,1)
np_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create an array of five values evenly spaced between 0 and 1
np_arr = np.linspace(0, 1, 5)

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np_arr = np.random.random((3, 3))
np_arr

array([[0.43455873, 0.08087447, 0.36308352],
       [0.39448802, 0.11953896, 0.84743223],
       [0.46513805, 0.93481964, 0.14021028]])

In [ ]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np_arr = np.random.normal(0, 1, (3, 3))
np_arr

array([[-1.04782034,  1.82743521, -0.06473692],
       [ 0.04328195, -0.04274667, -0.23197686],
       [-2.01079058,  0.40072256,  1.9761313 ]])

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[0, 3, 6],
       [7, 2, 9],
       [0, 0, 2]])

In [ ]:
np_arr

array([[-1.04782034,  1.82743521, -0.06473692],
       [ 0.04328195, -0.04274667, -0.23197686],
       [-2.01079058,  0.40072256,  1.9761313 ]])

In [ ]:
b.T

NameError: name 'b' is not defined

In [ ]:
np_arr 

In [ ]:
# Create an uninitialized arrays
# The values will be whatever happens to already exist at that memory location
np_arr = np.empty((5,2))

In [ ]:
np_arr

In [ ]:
np_arr=np.empty((5,2), dtype = np.int32)

In [ ]:
np_arr

In [ ]:
 # Create a length-10 integer array filled with zeros
np_arr = np.zeros((5,2))

In [ ]:
np_arr

In [ ]:
np_arr = np.ones((5,2))  # Create a 5x2 floating-point array filled with ones

In [ ]:
np_arr

In [ ]:
np_arr.ravel()

<script src="https://npmcdn.com/jupyter-js-widgets@~1.2.0/dist/embed.js"></script><img src='https://t1.daumcdn.net/cfile/tistory/99B4C23C5A884A392C'><script type="application/vnd.jupyter-embedded-widgets">{}</script>

In [3]:
import numpy as np
np_arr = np.eye(3) # 3 by b matrics=

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np_arr = np.full((2,2), 7) # Create a 2x2 array filled with 7

In [5]:
np_arr

array([[7, 7],
       [7, 7]])

### NumPy Data Types 

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

#### Practice 1
- Create an array of shape (2,3,4) of zeros
- Create an array of shape (3,4,5) of ones
- Create an array with values 0 to 49 using the np.arange() 

#### Practice  2    
- Create an array of from the list [2,5,5, -7.2, 3,5, 2.7, 4.7] and assign it 
  print np_arr[1] 
- try printing np_arr[1:-4] to see what the equals?
- Create a 2-D array from the following list and assign it 
  [[2, 3.2, 5.5, -6.4, -2.2, 2.4], 
  [1, 22, 4, 0.1, 5.3, -9], 
  [3, 1, 2.1, 21, 1.1, -2]]

- try printing the following
  a[:, 3], 
  a[1:4, 0:4], 
  a[1:, 2] 

In [ ]:
import numpy as np
np_arr = np.array([2,5.5, -7.2, 3.5, 2.7, 4.7])

In [ ]:
np_arr

In [ ]:
np_arr[1]

In [ ]:
np_arr[1:4]

In [ ]:
np_arr = np.array([[2, 3.2, 5.5, -6.4, -2.2, 2.4],
                [1, 22, 4, 0.1, 5.3, -9],
                [3, 1, 2.1, 21, 1.1, -2]])

In [ ]:
np_arr

In [ ]:
np_arr[:,3]

#### Practice 3
- Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it
- Check the shape, the size,n the maximum and minimum of the array 

- Contiunue to use the array as defined above. 
- print the array re-shaped to (2,2,2)
- print the array transposed
- print the array flattened to a single dimension

## 4. Mathematical Operations and Array Calculations 

NumPy n-dimensional arrays makes it extremely easy to perform mathematical operations on it.
- Mathematical operations with arrays
- Mathematical operations mixing scalars and arrays
- Comparison operators and Boolean operations on arrays
- Broadcasting

In [ ]:
py_arr = [1,2,3] * 2

In [ ]:
np_arr = np.array([1,2,3]) * 2 

In [ ]:
py_arr

[1, 2, 3, 1, 2, 3]

In [ ]:
np_arr

array([2, 4, 6])

multi dimensional mathematical operations

In [ ]:
np_arr = np.ones((5,2)) * 10

In [ ]:
np_arr

array([[10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.]])

#### Practice 4
- Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the   
  variable "a" 
- Create an array from a list [2, -1, 1, 0] and assign it to the variable "b"
- Multiply array "a" by "b" and view the result. Do you understand how NumPy has used its broadcasting feature
  to do the calculation even though the arrays are different shapes?
- Multiply array "b" by 100 and assign the result to the variable "b1".
- Multiply array "b" by 100.0 and assign the result to the variable "b2".
- Print the arrays "b1" and "b2".
- Print "b1 == b2". Are they the same?
- Why do they display differently? Interrogate the typecode of each array to find out why.

In [ ]:
import numpy as np

In [ ]:
a = np.array([range(4), range(10,14)])

In [ ]:
b = np.array([2,-1,1,0])

In [ ]:
# a*b

In [ ]:
# b1

In [ ]:
#b2

In [ ]:
#print 

### Broadcasting 
Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.


In [ ]:
import numpy as np

In [ ]:
a = np.array([0,1,2])
b = np.array([5,5,5])

In [ ]:
a+b

array([5, 6, 7])

Broadcasting allows these types of binary operations to be performed on arrays of different sizes–for example,
you can just as easily add a scalar (think of it as a zero-dimensional array) to an array:

In [ ]:
a+5

array([5, 6, 7])



You can think of this as an operation that stretches or duplicates the value 5 into the array [5, 5, 5], and adds the results. The advantage of NumPy's broadcasting is that this duplication of values does not actually take place, but it is a useful mental model as we think about broadcasting.

You can similarly extend this to arrays of higher dimension. Observe the result when we add a one-dimensional array to a two-dimensional array:


In [ ]:
c = np.ones((3,3))

In [ ]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
c + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])



Here the one-dimensional array a is stretched, or broadcast across the second dimension in order to match the shape of j.

While these examples are relatively easy to understand, more complicated cases can involve broadcasting of both arrays. Consider the following example:


In [ ]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

In [ ]:
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [ ]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Just as before we stretched or broadcasted one value to match the shape of the other, here we've stretched both a and b to match a common shape, and the result is a two-dimensional array! The geometry of these examples is visualized in the following figure 

<script src="https://npmcdn.com/jupyter-js-widgets@~1.2.0/dist/embed.js"></script><img src='https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png'><script type="application/vnd.jupyter-embedded-widgets">{}</script>

### Rules of Broadcasting

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

    1.Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is 
              padded with ones on its leading (left) side.
    2.Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that        
              dimension is stretched to match the other shape.
    3.Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

Thanks for your attention!!! 